import SwiftUI

/// App-level composition of the shared ``DesignTokens`` into the auth flow's
/// reusable surfaces. The raw color + shape values are the single source of
/// truth generated by `@infra/design` (shared with web / android / harmony);
/// this file only arranges them into the background, card, field, button,
/// banner and brand mark. No hand-picked colors live here.
enum AuthTheme {
    /// Serif display face for step titles, mirroring web's `font-serif` headings.
    static let title = Font.system(.title, design: .serif).weight(.medium)
}

/// Full-bleed warm-paper background used behind every step.
struct AuthBackground: View {
    var body: some View {
        DesignTokens.background.ignoresSafeArea()
    }
}

/// Brand lockup: a small clay dot + the tracked, uppercased wordmark. Matches
/// the header on web's auth card.
struct BrandMark: View {
    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(DesignTokens.primary)
                .frame(width: 8, height: 8)
            Text(AuthCopy.brand.uppercased())
                .font(.caption2.weight(.medium))
                .kerning(1.6)
                .foregroundStyle(DesignTokens.textSecondary)
        }
    }
}

/// Rounded surface card the step content sits in. The paper background and the
/// surface fill differ by <2% lightness, so a hairline border plus a soft
/// shadow keep the card readable against the page (never rely on fill alone).
struct AuthCard<Content: View>: View {
    @ViewBuilder var content: Content

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            content
        }
        .padding(24)
        .background(DesignTokens.surface,
                    in: RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous)
                .strokeBorder(DesignTokens.border, lineWidth: 1)
        )
        .padding(.horizontal, 20)
        .shadow(color: .black.opacity(0.06), radius: 16, y: 8)
    }
}

/// Inset chrome shared by the phone + code inputs: paper fill against the
/// surface card, hairline border, token radius.
private struct AuthFieldBackground: ViewModifier {
    func body(content: Content) -> some View {
        content
            .background(DesignTokens.background,
                        in: RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous)
                    .strokeBorder(DesignTokens.border, lineWidth: 1)
            )
    }
}

extension View {
    /// Applies the shared inset field chrome (fill + border + radius).
    func authFieldBackground() -> some View { modifier(AuthFieldBackground()) }
}

/// Filled clay primary button that shows a spinner while `loading`.
struct PrimaryButton: View {
    let title: String
    var loading = false
    var enabled = true
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            ZStack {
                Text(title).opacity(loading ? 0 : 1)
                if loading { ProgressView().tint(DesignTokens.primaryForeground) }
            }
            .font(.headline)
            .frame(maxWidth: .infinity)
            .frame(height: 52)
            .foregroundStyle(DesignTokens.primaryForeground)
            .background(DesignTokens.primary.opacity(enabled ? 1 : 0.4),
                        in: RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous))
        }
        .disabled(!enabled || loading)
    }
}

/// Inline error banner; renders nothing when `message` is nil. Mirrors web's
/// destructive-tinted alert: danger text on a faint danger wash + border.
struct ErrorBanner: View {
    let message: String?

    var body: some View {
        if let message {
            Label(message, systemImage: "exclamationmark.triangle.fill")
                .font(.footnote)
                .foregroundStyle(DesignTokens.danger)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, 12)
                .padding(.vertical, 10)
                .background(DesignTokens.danger.opacity(0.10),
                            in: RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous))
                .overlay(
                    RoundedRectangle(cornerRadius: DesignTokens.radius, style: .continuous)
                        .strokeBorder(DesignTokens.danger.opacity(0.3), lineWidth: 1)
                )
                .transition(.opacity)
        }
    }
}
