// GENERATED by @infra/design — DO NOT EDIT. Run `pnpm gen:design`.
package ai.deeplang.infra.ui.auth

import ai.deeplang.infra.data.contracts.AuthErrorCode

/** Canonical auth copy shared with web / ios / harmony. */
object AuthCopyGenerated {
    const val BRAND = "infra-lab"
    const val TAGLINE = "手机号，一步登录"

    const val PHONE_TITLE = "手机号登录"
    const val PHONE_DESCRIPTION = "未注册的手机号将自动创建账号。"
    const val PHONE_LABEL = "手机号"
    const val PHONE_PLACEHOLDER = "+8613800138000"
    const val PHONE_SUBMIT = "获取验证码"
    const val PHONE_SUBMIT_BUSY = "发送中…"

    const val CODE_TITLE = "输入验证码"
    const val CODE_LABEL = "6 位验证码"
    const val CODE_PLACEHOLDER = "••••••"
    const val CODE_SUBMIT = "登录 / 注册"
    const val CODE_SUBMIT_BUSY = "验证中…"
    const val CODE_RESEND = "重新发送"
    const val CODE_CHANGE_PHONE = "‹ 更换手机号"

    const val DONE_TITLE = "已登录"
    const val DONE_NEW_ACCOUNT = "欢迎加入，新账号已自动创建。"
    const val DONE_LOGOUT = "退出登录"

    const val FOOTER = "原生客户端（iOS / Android / HarmonyOS）将改用 Bearer accessToken + refreshToken。"

    const val ERROR_NETWORK = "网络异常，请稍后再试。"
    const val ERROR_GENERIC = "出错了，请稍后再试。"

    val errorMessages: Map<AuthErrorCode, String> = mapOf(
        AuthErrorCode.INVALID_REQUEST to "手机号或验证码格式不正确。",
        AuthErrorCode.RESEND_COOLDOWN to "发送过于频繁，请稍后再试。",
        AuthErrorCode.DAILY_LIMIT_EXCEEDED to "今日验证码发送次数已达上限。",
        AuthErrorCode.IP_LIMIT_EXCEEDED to "当前网络发送过于频繁，请稍后再试。",
        AuthErrorCode.LOCKED to "尝试次数过多，账号已被临时锁定，请 10 分钟后重试。",
        AuthErrorCode.CODE_EXPIRED to "验证码已过期，请重新获取。",
        AuthErrorCode.INVALID_CODE to "验证码错误。",
        AuthErrorCode.UNAUTHORIZED to "登录状态已失效，请重新登录。",
        AuthErrorCode.INVALID_REFRESH_TOKEN to "登录状态已失效，请重新登录。",
    )

    fun codeDescription(phone: String, minutes: Int): String =
        "验证码已发送至 {phone}，{minutes} 分钟内有效。".replace("{phone}", phone).replace("{minutes}", minutes.toString())

    fun resendCooldown(seconds: Int): String =
        "{seconds}s 后重新发送".replace("{seconds}", seconds.toString())

    fun invalidCodeRemaining(base: String, remaining: Int): String =
        "{base}还可尝试 {remaining} 次。".replace("{base}", base).replace("{remaining}", remaining.toString())
}
