package dev.w3ctech.infralab.ui.auth

import dev.w3ctech.infralab.data.AuthException
import dev.w3ctech.infralab.data.contracts.AuthErrorCode

/**
 * Maps a failure to user-facing copy. The wording itself lives in
 * [AuthCopyGenerated] (generated by @infra/design, shared with web / ios / harmony);
 * this only decides which string to show. Network/unknown failures collapse to a
 * generic message.
 */
object AuthMessages {
    fun describe(error: Throwable?): String {
        val authError = error as? AuthException ?: return AuthCopyGenerated.ERROR_NETWORK
        val base = authError.code?.let(AuthCopyGenerated.errorMessages::get) ?: AuthCopyGenerated.ERROR_GENERIC
        val remaining = authError.remainingAttempts
        return if (authError.code == AuthErrorCode.INVALID_CODE && remaining != null) {
            AuthCopyGenerated.invalidCodeRemaining(base, remaining)
        } else {
            base
        }
    }
}
