/**
 * Emit per-platform design artifacts (tokens + copy) from the canonical
 * `tokens.ts` / `copy.ts`. Run via `pnpm gen:design`.
 *
 * Every file this writes is marked `@generated` and must NOT be hand-edited: CI
 * re-runs this generator and fails on any `git diff`, so the only way to change a
 * client's brand color or auth wording is to change the source here. That is the
 * engineering constraint that keeps all four clients' UI consistent.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { AUTH_ERROR_CODES } from "@infra/shared";
import { COPY } from "./copy";
import { dark, light, oklchToCss, oklchToHex, type Palette, shape } from "./tokens";

// packages/design/src/generate.ts → repo root is three levels up.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

const written: string[] = [];
function write(relPath: string, content: string): void {
  const abs = join(ROOT, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content.endsWith("\n") ? content : `${content}\n`);
  written.push(relPath);
}

/** JSON-escape a string for double-quoted TS/Swift/Kotlin/JSON literals. */
const q = (s: string) => JSON.stringify(s);
const GEN = "GENERATED by @infra/design — DO NOT EDIT. Run `pnpm gen:design`.";

// Ordered role → CSS var name, matching web's original globals.css. `primaryDeep`
// is a native-only derived token and is intentionally not a web CSS variable.
const CSS_ROLES: [keyof Palette, string][] = [
  ["background", "background"],
  ["foreground", "foreground"],
  ["card", "card"],
  ["cardForeground", "card-foreground"],
  ["popover", "popover"],
  ["popoverForeground", "popover-foreground"],
  ["primary", "primary"],
  ["primaryForeground", "primary-foreground"],
  ["secondary", "secondary"],
  ["secondaryForeground", "secondary-foreground"],
  ["muted", "muted"],
  ["mutedForeground", "muted-foreground"],
  ["accent", "accent"],
  ["accentForeground", "accent-foreground"],
  ["destructive", "destructive"],
  ["destructiveForeground", "destructive-foreground"],
  ["border", "border"],
  ["input", "input"],
  ["ring", "ring"],
];

// ── web: CSS custom properties ────────────────────────────────────────────────
function emitWeb(): void {
  const block = (sel: string, p: Palette, withRadius: boolean) => {
    const lines = withRadius ? [`  --radius: ${shape.radiusPx / 16}rem;`] : [];
    for (const [role, name] of CSS_ROLES) lines.push(`  --${name}: ${oklchToCss(p[role])};`);
    return `${sel} {\n${lines.join("\n")}\n}`;
  };
  write(
    "apps/web/app/tokens.generated.css",
    `/* ${GEN} */\n\n${block(":root", light, true)}\n\n${block(".dark", dark, false)}\n`,
  );
}

// ── ios: SwiftUI tokens + copy ────────────────────────────────────────────────
const SWIFT_CASE: Record<string, string> = {
  INVALID_REQUEST: "invalidRequest",
  RESEND_COOLDOWN: "resendCooldown",
  DAILY_LIMIT_EXCEEDED: "dailyLimitExceeded",
  IP_LIMIT_EXCEEDED: "ipLimitExceeded",
  LOCKED: "locked",
  CODE_EXPIRED: "codeExpired",
  INVALID_CODE: "invalidCode",
  UNAUTHORIZED: "unauthorized",
  INVALID_REFRESH_TOKEN: "invalidRefreshToken",
};

function emitIos(): void {
  const color = (role: keyof Palette, name: string) =>
    `    static let ${name} = dyn(light: "${oklchToHex(light[role])}", dark: "${oklchToHex(dark[role])}")`;

  write(
    "apps/ios/InfraAuth/Generated/DesignTokens.swift",
    `// ${GEN}
import SwiftUI
import UIKit

/// Canonical color + shape tokens shared with web / android / harmony.
enum DesignTokens {
    static let radius: CGFloat = ${shape.radiusPx}
${color("primary", "primary")}
${color("primaryDeep", "primaryDeep")}
${color("primaryForeground", "primaryForeground")}
${color("background", "background")}
${color("card", "surface")}
${color("foreground", "textPrimary")}
${color("mutedForeground", "textSecondary")}
${color("destructive", "danger")}
${color("border", "border")}

    /// A Color that resolves light/dark per the active trait collection.
    private static func dyn(light: String, dark: String) -> Color {
        Color(UIColor { $0.userInterfaceStyle == .dark ? UIColor(hex: dark) : UIColor(hex: light) })
    }
}

private extension UIColor {
    convenience init(hex: String) {
        let s = hex.hasPrefix("#") ? String(hex.dropFirst()) : hex
        var v: UInt64 = 0
        Scanner(string: s).scanHexInt64(&v)
        self.init(
            red: CGFloat((v >> 16) & 0xFF) / 255,
            green: CGFloat((v >> 8) & 0xFF) / 255,
            blue: CGFloat(v & 0xFF) / 255,
            alpha: 1
        )
    }
}
`,
  );

  const errCases = AUTH_ERROR_CODES.map(
    (code) => `        case .${SWIFT_CASE[code]}: return ${q(COPY.errors.messages[code])}`,
  ).join("\n");

  write(
    "apps/ios/InfraAuth/Generated/AuthCopy.swift",
    `// ${GEN}
import Foundation

/// Canonical auth copy shared with web / android / harmony.
enum AuthCopy {
    static let brand = ${q(COPY.brand)}

    enum Phone {
        static let title = ${q(COPY.phone.title)}
        static let description = ${q(COPY.phone.description)}
        static let label = ${q(COPY.phone.label)}
        static let placeholder = ${q(COPY.phone.placeholder)}
        static let submit = ${q(COPY.phone.submit)}
        static let submitBusy = ${q(COPY.phone.submitBusy)}
    }

    enum Code {
        static let title = ${q(COPY.code.title)}
        static let label = ${q(COPY.code.label)}
        static let placeholder = ${q(COPY.code.placeholder)}
        static let submit = ${q(COPY.code.submit)}
        static let submitBusy = ${q(COPY.code.submitBusy)}
        static let resend = ${q(COPY.code.resend)}
        static let changePhone = ${q(COPY.code.changePhone)}

        static func description(phone: String, minutes: Int) -> String {
            ${q(COPY.code.description)}
                .replacingOccurrences(of: "{phone}", with: phone)
                .replacingOccurrences(of: "{minutes}", with: String(minutes))
        }
        static func resendCooldown(seconds: Int) -> String {
            ${q(COPY.code.resendCooldown)}.replacingOccurrences(of: "{seconds}", with: String(seconds))
        }
    }

    enum Done {
        static let title = ${q(COPY.done.title)}
        static let newAccount = ${q(COPY.done.newAccount)}
        static let logout = ${q(COPY.done.logout)}
    }

    static let footer = ${q(COPY.footer)}

    enum Errors {
        static let network = ${q(COPY.errors.network)}
        static let generic = ${q(COPY.errors.generic)}

        static func message(for code: AuthErrorCode) -> String {
            switch code {
${errCases}
            case .unknown: return generic
            }
        }
        static func invalidCodeRemaining(base: String, remaining: Int) -> String {
            ${q(COPY.errors.invalidCodeRemaining)}
                .replacingOccurrences(of: "{base}", with: base)
                .replacingOccurrences(of: "{remaining}", with: String(remaining))
        }
    }
}
`,
  );
}

// ── android: Compose tokens + copy ────────────────────────────────────────────
function emitAndroid(): void {
  const color = (role: keyof Palette, name: string, p: Palette) =>
    `        val ${name} = Color(0xFF${oklchToHex(p[role]).slice(1)})`;
  const scheme = (obj: string, p: Palette) =>
    `    object ${obj} {
${color("primary", "primary", p)}
${color("primaryDeep", "primaryDeep", p)}
${color("primaryForeground", "onPrimary", p)}
${color("background", "background", p)}
${color("card", "surface", p)}
${color("foreground", "onSurface", p)}
${color("mutedForeground", "onSurfaceVariant", p)}
${color("destructive", "danger", p)}
${color("border", "outline", p)}
    }`;

  write(
    "apps/android/app/src/main/kotlin/ai/deeplang/infra/ui/theme/DesignTokens.kt",
    `// ${GEN}
package ai.deeplang.infra.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

/** Canonical color + shape tokens shared with web / ios / harmony. */
object DesignTokens {
    val radius = ${shape.radiusPx}.dp

${scheme("Light", light)}

${scheme("Dark", dark)}
}
`,
  );

  const errEntries = AUTH_ERROR_CODES.map(
    (code) => `        AuthErrorCode.${code} to ${q(COPY.errors.messages[code])},`,
  ).join("\n");

  write(
    "apps/android/app/src/main/kotlin/ai/deeplang/infra/ui/auth/AuthCopyGenerated.kt",
    `// ${GEN}
package ai.deeplang.infra.ui.auth

import ai.deeplang.infra.data.contracts.AuthErrorCode

/** Canonical auth copy shared with web / ios / harmony. */
object AuthCopyGenerated {
    const val BRAND = ${q(COPY.brand)}

    const val PHONE_TITLE = ${q(COPY.phone.title)}
    const val PHONE_DESCRIPTION = ${q(COPY.phone.description)}
    const val PHONE_LABEL = ${q(COPY.phone.label)}
    const val PHONE_PLACEHOLDER = ${q(COPY.phone.placeholder)}
    const val PHONE_SUBMIT = ${q(COPY.phone.submit)}
    const val PHONE_SUBMIT_BUSY = ${q(COPY.phone.submitBusy)}

    const val CODE_TITLE = ${q(COPY.code.title)}
    const val CODE_LABEL = ${q(COPY.code.label)}
    const val CODE_PLACEHOLDER = ${q(COPY.code.placeholder)}
    const val CODE_SUBMIT = ${q(COPY.code.submit)}
    const val CODE_SUBMIT_BUSY = ${q(COPY.code.submitBusy)}
    const val CODE_RESEND = ${q(COPY.code.resend)}
    const val CODE_CHANGE_PHONE = ${q(COPY.code.changePhone)}

    const val DONE_TITLE = ${q(COPY.done.title)}
    const val DONE_NEW_ACCOUNT = ${q(COPY.done.newAccount)}
    const val DONE_LOGOUT = ${q(COPY.done.logout)}

    const val FOOTER = ${q(COPY.footer)}

    const val ERROR_NETWORK = ${q(COPY.errors.network)}
    const val ERROR_GENERIC = ${q(COPY.errors.generic)}

    val errorMessages: Map<AuthErrorCode, String> = mapOf(
${errEntries}
    )

    fun codeDescription(phone: String, minutes: Int): String =
        ${q(COPY.code.description)}.replace("{phone}", phone).replace("{minutes}", minutes.toString())

    fun resendCooldown(seconds: Int): String =
        ${q(COPY.code.resendCooldown)}.replace("{seconds}", seconds.toString())

    fun invalidCodeRemaining(base: String, remaining: Int): String =
        ${q(COPY.errors.invalidCodeRemaining)}.replace("{base}", base).replace("{remaining}", remaining.toString())
}
`,
  );
}

// ── harmony: ArkUI color resource + copy ──────────────────────────────────────
function emitHarmony(): void {
  // Keep the resource names the entry module already references.
  const colors = [
    { name: "start_window_background", role: "background" as const },
    { name: "brand", role: "primary" as const },
    { name: "page_background", role: "background" as const },
    { name: "surface", role: "card" as const },
    { name: "text_primary", role: "foreground" as const },
    { name: "text_secondary", role: "mutedForeground" as const },
    { name: "danger", role: "destructive" as const },
  ];
  write(
    "apps/harmony/entry/src/main/resources/base/element/color.json",
    `${JSON.stringify(
      { color: colors.map((c) => ({ name: c.name, value: oklchToHex(light[c.role]) })) },
      null,
      2,
    )}\n`,
  );

  const errCases = AUTH_ERROR_CODES.map(
    (code) => `    case ${q(code)}:\n      return ${q(COPY.errors.messages[code])};`,
  ).join("\n");

  // ArkTS forbids untyped object literals, so copy is emitted as flat consts.
  write(
    "apps/harmony/entry/src/main/ets/sdk/copy.generated.ets",
    `// ${GEN}
import { AuthErrorCode } from "../common/contracts";

/** Canonical auth copy shared with web / ios / android. */
export const BRAND: string = ${q(COPY.brand)};

export const PHONE_TITLE: string = ${q(COPY.phone.title)};
export const PHONE_DESCRIPTION: string = ${q(COPY.phone.description)};
export const PHONE_LABEL: string = ${q(COPY.phone.label)};
export const PHONE_PLACEHOLDER: string = ${q(COPY.phone.placeholder)};
export const PHONE_SUBMIT: string = ${q(COPY.phone.submit)};
export const PHONE_SUBMIT_BUSY: string = ${q(COPY.phone.submitBusy)};

export const CODE_TITLE: string = ${q(COPY.code.title)};
export const CODE_LABEL: string = ${q(COPY.code.label)};
export const CODE_PLACEHOLDER: string = ${q(COPY.code.placeholder)};
export const CODE_SUBMIT: string = ${q(COPY.code.submit)};
export const CODE_SUBMIT_BUSY: string = ${q(COPY.code.submitBusy)};
export const CODE_RESEND: string = ${q(COPY.code.resend)};
export const CODE_CHANGE_PHONE: string = ${q(COPY.code.changePhone)};

export const DONE_TITLE: string = ${q(COPY.done.title)};
export const DONE_NEW_ACCOUNT: string = ${q(COPY.done.newAccount)};
export const DONE_LOGOUT: string = ${q(COPY.done.logout)};

export const FOOTER: string = ${q(COPY.footer)};

export const ERROR_NETWORK: string = ${q(COPY.errors.network)};
export const ERROR_GENERIC: string = ${q(COPY.errors.generic)};

export function errorMessageFor(code: AuthErrorCode): string {
  switch (code) {
${errCases}
    default:
      return ERROR_GENERIC;
  }
}

export function codeDescription(phone: string, minutes: number): string {
  return ${q(COPY.code.description)}.replace("{phone}", phone).replace("{minutes}", \`\${minutes}\`);
}

export function resendCooldown(seconds: number): string {
  return ${q(COPY.code.resendCooldown)}.replace("{seconds}", \`\${seconds}\`);
}

export function invalidCodeRemaining(base: string, remaining: number): string {
  return ${q(COPY.errors.invalidCodeRemaining)}.replace("{base}", base).replace("{remaining}", \`\${remaining}\`);
}
`,
  );
}

emitWeb();
emitIos();
emitAndroid();
emitHarmony();

console.log(`@infra/design: generated ${written.length} files`);
for (const f of written) console.log(`  ${f}`);
