// GENERATED by @infra/design — DO NOT EDIT. Run `pnpm gen:design`.
package dev.w3ctech.infralab.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

/** Canonical color + shape tokens shared with web / ios / harmony. */
object DesignTokens {
    val radius = 10.dp

    object Light {
        val primary = Color(0xFFB95115)
        val primaryDeep = Color(0xFF952400)
        val onPrimary = Color(0xFFFDFCF8)
        val background = Color(0xFFFCFAF4)
        val surface = Color(0xFFFFFEFB)
        val onSurface = Color(0xFF29231E)
        val onSurfaceVariant = Color(0xFF6E6762)
        val danger = Color(0xFFC53732)
        val outline = Color(0xFFE0DED8)
    }

    object Dark {
        val primary = Color(0xFFDF8352)
        val primaryDeep = Color(0xFFB95115)
        val onPrimary = Color(0xFF1E130E)
        val background = Color(0xFF13110F)
        val surface = Color(0xFF1C1916)
        val onSurface = Color(0xFFEAE7E3)
        val onSurfaceVariant = Color(0xFFA5A19B)
        val danger = Color(0xFFC74B47)
        val outline = Color(0xFF302D2A)
    }
}
