package dev.w3ctech.infralab.ui.theme

import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext

// Colors come from `DesignTokens` (generated by @infra/design), the single source
// shared with web / ios / harmony. Do not hand-pick colors here — change them at
// the source and run `pnpm gen:design`.
private val LightColors = lightColorScheme(
    primary = DesignTokens.Light.primary,
    onPrimary = DesignTokens.Light.onPrimary,
    background = DesignTokens.Light.background,
    onBackground = DesignTokens.Light.onSurface,
    surface = DesignTokens.Light.surface,
    onSurface = DesignTokens.Light.onSurface,
    onSurfaceVariant = DesignTokens.Light.onSurfaceVariant,
    error = DesignTokens.Light.danger,
    outline = DesignTokens.Light.outline,
)

private val DarkColors = darkColorScheme(
    primary = DesignTokens.Dark.primary,
    onPrimary = DesignTokens.Dark.onPrimary,
    background = DesignTokens.Dark.background,
    onBackground = DesignTokens.Dark.onSurface,
    surface = DesignTokens.Dark.surface,
    onSurface = DesignTokens.Dark.onSurface,
    onSurfaceVariant = DesignTokens.Dark.onSurfaceVariant,
    error = DesignTokens.Dark.danger,
    outline = DesignTokens.Dark.outline,
)

@Composable
fun InfraTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Off by default: the canonical brand palette IS the design, so Material You
    // wallpaper colors would defeat cross-client consistency. Callers may opt in.
    dynamicColor: Boolean = false,
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S ->
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        darkTheme -> DarkColors
        else -> LightColors
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = MaterialTheme.typography,
        content = content,
    )
}
